rabbit:
  producer:
    druid:
      jdbc:
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall,log4j
        initialSize: 5
        maxActive: 100
        maxPoolPreparedStatementPerConnectionSize: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 1
        password: root
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        url: jdbc:mysql://8.131.57.243:3306/mall2?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&serverTimezone=GMT
        useGlobalDataSourceStat: true
        username: root
        validationQuery: SELECT 1 FROM DUAL
      type: com.alibaba.druid.pool.DruidDataSource