# 配置交换机
order:
  exchange:
    name: order-exchange
    durable: true
    type: topic
    key: order.*

server:
  port: 8065
  servlet:
    context-path: /



spring:
  rabbitmq:
    addresses: 8.131.57.243:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        # 消费者消费成功消息以后需要手工进行签收 ack，默认为auto
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
