server:
  port: 8060
  servlet:
    context-path: /



spring:
  rabbitmq:
    addresses: 8.131.57.243:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true
    # 设置消息模式 以下2个要一起使用
    publisher-returns: true
    template:
      mandatory: true