##################################################
#
# web访问端口  约定8088
#
##################################################
server:
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB
spring:
  profiles:
    #    active: dev          #   云服务器测试环境
    active: local        #    本地测试环境
  rabbitmq:
    addresses: 8.131.57.243:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      direct:
        auto-startup: false

elastic:
  job:
    zk:
      server-lists: 8.131.57.243:2181
      namespace: elastic-job
  ##################################################
  #
  # 配置数据源信息
  #
  ##################################################
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000                     # 连接超时时长
      minimum-idle: 5                               # 最小连接数
      maximum-pool-size: 20                         # 最大连接数
      auto-commit: true                             # 自动提交
      idle-timeout: 6000000                         # 连接超时的最大时长
      pool-name: DataSourceHikariCP                 # 连接池名字
      max-lifetime: 1800000                         # 连接的生命时长
      connection-test-query: Select 1               # select
  ##################################################
  #
  # 配置请求最大能有多大
  #
  ##################################################
  servlet:
    multipart:
      max-request-size: 512000                      # 请求大小限制
      max-file-size: 512000                         # 文件上传大小限制
  ##################################################
  #
  # 配置session 存储在那个里面
  #
  ##################################################
  session:
    store-type: redis                               # session存储类型
##################################################
#
# mybatis 配置
#
##################################################
mybatis-plus:
  type-aliases-package: com.like.pojo               # 所有实体类所在的包路径
  mapper-locations: classpath:mapper/*.xml          # mapper映射文件
  global-config:
    banner: false
